#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication fluentMeshToFoam LI_MRF_Pellet_Extruder.msh

runApplication topoSet
runApplication setsToZones

decomposePar

mpirun -np 4 rhoPimpleFoam -parallel > log & tail -f log # rausgenommen für Bash-Bearbeitung Scheid
 
echo "Done!"
#------------------------------------------------------------------------------
