#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication fluentMeshToFoam AMI.msh

#Create cellZones and faceZones for rotating mesh. Develop new AMI BC´s
runApplication topoSet

# Renumbering for speeding up simulation
runApplication renumberMesh -noFields -overwrite
exit
decomposePar

pyFoamPlotRunner.py mpirun -np 6 rhoPimpleFoam -parallel
 
echo "Done!"
#------------------------------------------------------------------------------
