#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication fluentMeshToFoam MRF.msh

runApplication topoSet
runApplication setsToZones

decomposePar

mpirun -np 6 polymSimpleFoam -parallel > log & tail -f log # rausgenommen für Bash-Bearbeitung Scheid
 
echo "Done!"
#------------------------------------------------------------------------------
