#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  05 Juli 2020                       #
#-------------------------------------------------#
# Topic:       AMI FAN Tutorial and SnappyHexMesh #
# OpenFOAM:    7.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
fluentMeshToFoam cad/background.msh

#------------------------------------------------------------------------------
echo -e "   - Extract surface features"
surfaceFeatureExtract


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh (~ 120 seconds)"
snappyHexMesh -overwrite 


#------------------------------------------------------------------------------
echo -e "   - Create Baffles"
createBaffles -overwrite 


#------------------------------------------------------------------------------
echo -e "   - Split Baffles to allow sliding. If this step is not done, the"
echo -e "     moving and static mesh part are still connected"
mergeOrSplitBaffles -split -overwrite 


#------------------------------------------------------------------------------
echo -e "   - Renumber the mesh for optimizing the matrix"
renumberMesh -overwrite 


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.orig to 0"
cp -r 0.orig 0



#------------------------------------------------------------------------------
