#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf PyFoam*
rm -rf Gnuplotting.analyzed
rm -rf constant/extendedFeatureEdgeMesh
rm -rf constant/triSurface/AMI.eMesh
rm -rf constant/triSurface/pelletExtruder.eMesh
rm -rf continuity*
rm -rf linear*
rm static.foam

echo "Done!"
#------------------------------------------------------------------------------
